/*
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendbirdDisappearingMessage
 */
public class SendbirdDisappearingMessageTest {
    private final SendbirdDisappearingMessage model = new SendbirdDisappearingMessage();

    /**
     * Model tests for SendbirdDisappearingMessage
     */
    @Test
    public void testSendbirdDisappearingMessage() {
        // TODO: test SendbirdDisappearingMessage
    }

    /**
     * Test the property 'messageSurvivalSeconds'
     */
    @Test
    public void messageSurvivalSecondsTest() {
        // TODO: test messageSurvivalSeconds
    }

    /**
     * Test the property 'isTriggeredByMessageRead'
     */
    @Test
    public void isTriggeredByMessageReadTest() {
        // TODO: test isTriggeredByMessageRead
    }

}
