/*
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList;

/**
 * BanUsersInChannelsWithCustomChannelTypeData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-29T11:00:21.022543+01:00[Europe/London]")
public class BanUsersInChannelsWithCustomChannelTypeData {
  public static final String SERIALIZED_NAME_BANNED_LIST = "banned_list";
  @SerializedName(SERIALIZED_NAME_BANNED_LIST)
  private List<V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList> bannedList = new ArrayList<V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList>();

  public static final String SERIALIZED_NAME_ON_DEMAND_UPSERT = "on_demand_upsert";
  @SerializedName(SERIALIZED_NAME_ON_DEMAND_UPSERT)
  private Boolean onDemandUpsert;

  public BanUsersInChannelsWithCustomChannelTypeData() { 
  }

  public BanUsersInChannelsWithCustomChannelTypeData bannedList(List<V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList> bannedList) {
    
    this.bannedList = bannedList;
    return this;
  }

  public BanUsersInChannelsWithCustomChannelTypeData addBannedListItem(V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList bannedListItem) {
    this.bannedList.add(bannedListItem);
    return this;
  }

   /**
   * Get bannedList
   * @return bannedList
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList> getBannedList() {
    return bannedList;
  }


  public void setBannedList(List<V3ApplicationsSettingsByChannelCustomTypeCustomTypeBanBannedList> bannedList) {
    this.bannedList = bannedList;
  }


  public BanUsersInChannelsWithCustomChannelTypeData onDemandUpsert(Boolean onDemandUpsert) {
    
    this.onDemandUpsert = onDemandUpsert;
    return this;
  }

   /**
   * Get onDemandUpsert
   * @return onDemandUpsert
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOnDemandUpsert() {
    return onDemandUpsert;
  }


  public void setOnDemandUpsert(Boolean onDemandUpsert) {
    this.onDemandUpsert = onDemandUpsert;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BanUsersInChannelsWithCustomChannelTypeData banUsersInChannelsWithCustomChannelTypeData = (BanUsersInChannelsWithCustomChannelTypeData) o;
    return Objects.equals(this.bannedList, banUsersInChannelsWithCustomChannelTypeData.bannedList) &&
        Objects.equals(this.onDemandUpsert, banUsersInChannelsWithCustomChannelTypeData.onDemandUpsert);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bannedList, onDemandUpsert);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BanUsersInChannelsWithCustomChannelTypeData {\n");
    sb.append("    bannedList: ").append(toIndentedString(bannedList)).append("\n");
    sb.append("    onDemandUpsert: ").append(toIndentedString(onDemandUpsert)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

