/*
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.GetAGroupChannelResponseAllOf;
import org.openapitools.client.model.SendbirdBasicUserInfo;
import org.openapitools.client.model.SendbirdDisappearingMessage;
import org.openapitools.client.model.SendbirdGroupChannel;
import org.openapitools.client.model.SendbirdGroupChannelDetailChannel;
import org.openapitools.client.model.SendbirdMember;
import org.openapitools.client.model.SendbirdMessageResponse;
import org.openapitools.client.model.SendbirdPushTriggerOption;
import org.openapitools.client.model.SendbirdSmsFallback;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.sendbird.client.JSON;


/**
 * GetAGroupChannelResponse
 */
@JsonPropertyOrder({
  GetAGroupChannelResponse.JSON_PROPERTY_CHANNEL,
  GetAGroupChannelResponse.JSON_PROPERTY_CHANNEL_URL,
  GetAGroupChannelResponse.JSON_PROPERTY_COUNT_PREFERENCE,
  GetAGroupChannelResponse.JSON_PROPERTY_COVER_URL,
  GetAGroupChannelResponse.JSON_PROPERTY_CREATED_AT,
  GetAGroupChannelResponse.JSON_PROPERTY_CREATED_BY,
  GetAGroupChannelResponse.JSON_PROPERTY_CUSTOM_TYPE,
  GetAGroupChannelResponse.JSON_PROPERTY_DATA,
  GetAGroupChannelResponse.JSON_PROPERTY_DELIVERY_RECEIPT,
  GetAGroupChannelResponse.JSON_PROPERTY_DISAPPEARING_MESSAGE,
  GetAGroupChannelResponse.JSON_PROPERTY_FREEZE,
  GetAGroupChannelResponse.JSON_PROPERTY_HAS_AI_BOT,
  GetAGroupChannelResponse.JSON_PROPERTY_HAS_BOT,
  GetAGroupChannelResponse.JSON_PROPERTY_HIDDEN_STATE,
  GetAGroupChannelResponse.JSON_PROPERTY_IGNORE_PROFANITY_FILTER,
  GetAGroupChannelResponse.JSON_PROPERTY_INVITED_AT,
  GetAGroupChannelResponse.JSON_PROPERTY_INVITER,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_ACCESS_CODE_REQUIRED,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_BROADCAST,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_DISCOVERABLE,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_DISTINCT,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_EPHEMERAL,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_EXCLUSIVE,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_HIDDEN,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_MUTED,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_PUBLIC,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_PUSH_ENABLED,
  GetAGroupChannelResponse.JSON_PROPERTY_IS_SUPER,
  GetAGroupChannelResponse.JSON_PROPERTY_JOINED_MEMBER_COUNT,
  GetAGroupChannelResponse.JSON_PROPERTY_JOINED_TS,
  GetAGroupChannelResponse.JSON_PROPERTY_LAST_MESSAGE,
  GetAGroupChannelResponse.JSON_PROPERTY_MAX_LENGTH_MESSAGE,
  GetAGroupChannelResponse.JSON_PROPERTY_MEMBER_COUNT,
  GetAGroupChannelResponse.JSON_PROPERTY_MEMBER_STATE,
  GetAGroupChannelResponse.JSON_PROPERTY_MEMBERS,
  GetAGroupChannelResponse.JSON_PROPERTY_MESSAGE_SURVIVAL_SECONDS,
  GetAGroupChannelResponse.JSON_PROPERTY_METADATA,
  GetAGroupChannelResponse.JSON_PROPERTY_MY_ROLE,
  GetAGroupChannelResponse.JSON_PROPERTY_NAME,
  GetAGroupChannelResponse.JSON_PROPERTY_PUSH_TRIGGER_OPTION,
  GetAGroupChannelResponse.JSON_PROPERTY_READ_RECEIPT,
  GetAGroupChannelResponse.JSON_PROPERTY_SMS_FALLBACK,
  GetAGroupChannelResponse.JSON_PROPERTY_TS_MESSAGE_OFFSET,
  GetAGroupChannelResponse.JSON_PROPERTY_UNREAD_MENTION_COUNT,
  GetAGroupChannelResponse.JSON_PROPERTY_UNREAD_MESSAGE_COUNT,
  GetAGroupChannelResponse.JSON_PROPERTY_USER_LAST_READ
})
@JsonTypeName("getAGroupChannelResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-16T10:11:20.822211+07:00[Asia/Jakarta]")
public class GetAGroupChannelResponse {
  public static final String JSON_PROPERTY_CHANNEL = "channel";
  private SendbirdGroupChannelDetailChannel channel;

  public static final String JSON_PROPERTY_CHANNEL_URL = "channel_url";
  private String channelUrl;

  /**
   * Gets or Sets countPreference
   */
  public enum CountPreferenceEnum {
    FALSE("false"),
    
    ALL("all"),
    
    UNREAD_MESSAGE_COUNT_ONLY("unread_message_count_only"),
    
    UNREAD_MENTIONED_COUNT_ONLY("unread_mentioned_count_only");

    private String value;

    CountPreferenceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CountPreferenceEnum fromValue(String value) {
      for (CountPreferenceEnum b : CountPreferenceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COUNT_PREFERENCE = "count_preference";
  private CountPreferenceEnum countPreference;

  public static final String JSON_PROPERTY_COVER_URL = "cover_url";
  private String coverUrl;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private Long createdAt;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private SendbirdBasicUserInfo createdBy;

  public static final String JSON_PROPERTY_CUSTOM_TYPE = "custom_type";
  private String customType;

  public static final String JSON_PROPERTY_DATA = "data";
  private String data;

  public static final String JSON_PROPERTY_DELIVERY_RECEIPT = "delivery_receipt";
  private Object deliveryReceipt;

  public static final String JSON_PROPERTY_DISAPPEARING_MESSAGE = "disappearing_message";
  private SendbirdDisappearingMessage disappearingMessage;

  public static final String JSON_PROPERTY_FREEZE = "freeze";
  private Boolean freeze;

  public static final String JSON_PROPERTY_HAS_AI_BOT = "has_ai_bot";
  private Boolean hasAiBot;

  public static final String JSON_PROPERTY_HAS_BOT = "has_bot";
  private Boolean hasBot;

  /**
   * Gets or Sets hiddenState
   */
  public enum HiddenStateEnum {
    HIDDEN_ALLOW_AUTO_UNHIDE("hidden_allow_auto_unhide"),
    
    HIDDEN_PREVENT_AUTO_UNHIDE("hidden_prevent_auto_unhide"),
    
    UNHIDDEN("unhidden");

    private String value;

    HiddenStateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HiddenStateEnum fromValue(String value) {
      for (HiddenStateEnum b : HiddenStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_HIDDEN_STATE = "hidden_state";
  private HiddenStateEnum hiddenState;

  public static final String JSON_PROPERTY_IGNORE_PROFANITY_FILTER = "ignore_profanity_filter";
  private Boolean ignoreProfanityFilter;

  public static final String JSON_PROPERTY_INVITED_AT = "invited_at";
  private Long invitedAt;

  public static final String JSON_PROPERTY_INVITER = "inviter";
  private SendbirdBasicUserInfo inviter;

  public static final String JSON_PROPERTY_IS_ACCESS_CODE_REQUIRED = "is_access_code_required";
  private Boolean isAccessCodeRequired;

  public static final String JSON_PROPERTY_IS_BROADCAST = "is_broadcast";
  private Boolean isBroadcast;

  public static final String JSON_PROPERTY_IS_DISCOVERABLE = "is_discoverable";
  private Boolean isDiscoverable;

  public static final String JSON_PROPERTY_IS_DISTINCT = "is_distinct";
  private Boolean isDistinct;

  public static final String JSON_PROPERTY_IS_EPHEMERAL = "is_ephemeral";
  private Boolean isEphemeral;

  public static final String JSON_PROPERTY_IS_EXCLUSIVE = "is_exclusive";
  private Boolean isExclusive;

  public static final String JSON_PROPERTY_IS_HIDDEN = "is_hidden";
  private Boolean isHidden;

  public static final String JSON_PROPERTY_IS_MUTED = "is_muted";
  private Boolean isMuted;

  public static final String JSON_PROPERTY_IS_PUBLIC = "is_public";
  private Boolean isPublic;

  public static final String JSON_PROPERTY_IS_PUSH_ENABLED = "is_push_enabled";
  private Boolean isPushEnabled;

  public static final String JSON_PROPERTY_IS_SUPER = "is_super";
  private Boolean isSuper;

  public static final String JSON_PROPERTY_JOINED_MEMBER_COUNT = "joined_member_count";
  private Integer joinedMemberCount;

  public static final String JSON_PROPERTY_JOINED_TS = "joined_ts";
  private Long joinedTs;

  public static final String JSON_PROPERTY_LAST_MESSAGE = "last_message";
  private JsonNullable<SendbirdMessageResponse> lastMessage = JsonNullable.<SendbirdMessageResponse>undefined();

  public static final String JSON_PROPERTY_MAX_LENGTH_MESSAGE = "max_length_message";
  private Integer maxLengthMessage;

  public static final String JSON_PROPERTY_MEMBER_COUNT = "member_count";
  private Integer memberCount;

  /**
   * Gets or Sets memberState
   */
  public enum MemberStateEnum {
    INVITED("invited"),
    
    JOINED("joined"),
    
    NONE("none");

    private String value;

    MemberStateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MemberStateEnum fromValue(String value) {
      for (MemberStateEnum b : MemberStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MEMBER_STATE = "member_state";
  private MemberStateEnum memberState;

  public static final String JSON_PROPERTY_MEMBERS = "members";
  private List<SendbirdMember> members = null;

  public static final String JSON_PROPERTY_MESSAGE_SURVIVAL_SECONDS = "message_survival_seconds";
  private Integer messageSurvivalSeconds;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Object metadata;

  /**
   * Gets or Sets myRole
   */
  public enum MyRoleEnum {
    EMPTY(""),
    
    NONE("none"),
    
    OPERATOR("operator");

    private String value;

    MyRoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MyRoleEnum fromValue(String value) {
      for (MyRoleEnum b : MyRoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MY_ROLE = "my_role";
  private MyRoleEnum myRole;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PUSH_TRIGGER_OPTION = "push_trigger_option";
  private SendbirdPushTriggerOption pushTriggerOption;

  public static final String JSON_PROPERTY_READ_RECEIPT = "read_receipt";
  private Map<String, Long> readReceipt = null;

  public static final String JSON_PROPERTY_SMS_FALLBACK = "sms_fallback";
  private SendbirdSmsFallback smsFallback;

  public static final String JSON_PROPERTY_TS_MESSAGE_OFFSET = "ts_message_offset";
  private Long tsMessageOffset;

  public static final String JSON_PROPERTY_UNREAD_MENTION_COUNT = "unread_mention_count";
  private Integer unreadMentionCount;

  public static final String JSON_PROPERTY_UNREAD_MESSAGE_COUNT = "unread_message_count";
  private Integer unreadMessageCount;

  public static final String JSON_PROPERTY_USER_LAST_READ = "user_last_read";
  private Long userLastRead;

  public GetAGroupChannelResponse() { 
  }

  public GetAGroupChannelResponse channel(SendbirdGroupChannelDetailChannel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SendbirdGroupChannelDetailChannel getChannel() {
    return channel;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannel(SendbirdGroupChannelDetailChannel channel) {
    this.channel = channel;
  }


  public GetAGroupChannelResponse channelUrl(String channelUrl) {
    this.channelUrl = channelUrl;
    return this;
  }

   /**
   * Get channelUrl
   * @return channelUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CHANNEL_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChannelUrl() {
    return channelUrl;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChannelUrl(String channelUrl) {
    this.channelUrl = channelUrl;
  }


  public GetAGroupChannelResponse countPreference(CountPreferenceEnum countPreference) {
    this.countPreference = countPreference;
    return this;
  }

   /**
   * Get countPreference
   * @return countPreference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COUNT_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CountPreferenceEnum getCountPreference() {
    return countPreference;
  }


  @JsonProperty(JSON_PROPERTY_COUNT_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountPreference(CountPreferenceEnum countPreference) {
    this.countPreference = countPreference;
  }


  public GetAGroupChannelResponse coverUrl(String coverUrl) {
    this.coverUrl = coverUrl;
    return this;
  }

   /**
   * Get coverUrl
   * @return coverUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COVER_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCoverUrl() {
    return coverUrl;
  }


  @JsonProperty(JSON_PROPERTY_COVER_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoverUrl(String coverUrl) {
    this.coverUrl = coverUrl;
  }


  public GetAGroupChannelResponse createdAt(Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(Long createdAt) {
    this.createdAt = createdAt;
  }


  public GetAGroupChannelResponse createdBy(SendbirdBasicUserInfo createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SendbirdBasicUserInfo getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(SendbirdBasicUserInfo createdBy) {
    this.createdBy = createdBy;
  }


  public GetAGroupChannelResponse customType(String customType) {
    this.customType = customType;
    return this;
  }

   /**
   * Get customType
   * @return customType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomType() {
    return customType;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomType(String customType) {
    this.customType = customType;
  }


  public GetAGroupChannelResponse data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(String data) {
    this.data = data;
  }


  public GetAGroupChannelResponse deliveryReceipt(Object deliveryReceipt) {
    this.deliveryReceipt = deliveryReceipt;
    return this;
  }

   /**
   * Get deliveryReceipt
   * @return deliveryReceipt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_RECEIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getDeliveryReceipt() {
    return deliveryReceipt;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_RECEIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryReceipt(Object deliveryReceipt) {
    this.deliveryReceipt = deliveryReceipt;
  }


  public GetAGroupChannelResponse disappearingMessage(SendbirdDisappearingMessage disappearingMessage) {
    this.disappearingMessage = disappearingMessage;
    return this;
  }

   /**
   * Get disappearingMessage
   * @return disappearingMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISAPPEARING_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SendbirdDisappearingMessage getDisappearingMessage() {
    return disappearingMessage;
  }


  @JsonProperty(JSON_PROPERTY_DISAPPEARING_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisappearingMessage(SendbirdDisappearingMessage disappearingMessage) {
    this.disappearingMessage = disappearingMessage;
  }


  public GetAGroupChannelResponse freeze(Boolean freeze) {
    this.freeze = freeze;
    return this;
  }

   /**
   * Get freeze
   * @return freeze
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FREEZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFreeze() {
    return freeze;
  }


  @JsonProperty(JSON_PROPERTY_FREEZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFreeze(Boolean freeze) {
    this.freeze = freeze;
  }


  public GetAGroupChannelResponse hasAiBot(Boolean hasAiBot) {
    this.hasAiBot = hasAiBot;
    return this;
  }

   /**
   * Get hasAiBot
   * @return hasAiBot
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAS_AI_BOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasAiBot() {
    return hasAiBot;
  }


  @JsonProperty(JSON_PROPERTY_HAS_AI_BOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasAiBot(Boolean hasAiBot) {
    this.hasAiBot = hasAiBot;
  }


  public GetAGroupChannelResponse hasBot(Boolean hasBot) {
    this.hasBot = hasBot;
    return this;
  }

   /**
   * Get hasBot
   * @return hasBot
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAS_BOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasBot() {
    return hasBot;
  }


  @JsonProperty(JSON_PROPERTY_HAS_BOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasBot(Boolean hasBot) {
    this.hasBot = hasBot;
  }


  public GetAGroupChannelResponse hiddenState(HiddenStateEnum hiddenState) {
    this.hiddenState = hiddenState;
    return this;
  }

   /**
   * Get hiddenState
   * @return hiddenState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HIDDEN_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HiddenStateEnum getHiddenState() {
    return hiddenState;
  }


  @JsonProperty(JSON_PROPERTY_HIDDEN_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHiddenState(HiddenStateEnum hiddenState) {
    this.hiddenState = hiddenState;
  }


  public GetAGroupChannelResponse ignoreProfanityFilter(Boolean ignoreProfanityFilter) {
    this.ignoreProfanityFilter = ignoreProfanityFilter;
    return this;
  }

   /**
   * Get ignoreProfanityFilter
   * @return ignoreProfanityFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IGNORE_PROFANITY_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIgnoreProfanityFilter() {
    return ignoreProfanityFilter;
  }


  @JsonProperty(JSON_PROPERTY_IGNORE_PROFANITY_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIgnoreProfanityFilter(Boolean ignoreProfanityFilter) {
    this.ignoreProfanityFilter = ignoreProfanityFilter;
  }


  public GetAGroupChannelResponse invitedAt(Long invitedAt) {
    this.invitedAt = invitedAt;
    return this;
  }

   /**
   * Get invitedAt
   * @return invitedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INVITED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getInvitedAt() {
    return invitedAt;
  }


  @JsonProperty(JSON_PROPERTY_INVITED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvitedAt(Long invitedAt) {
    this.invitedAt = invitedAt;
  }


  public GetAGroupChannelResponse inviter(SendbirdBasicUserInfo inviter) {
    this.inviter = inviter;
    return this;
  }

   /**
   * Get inviter
   * @return inviter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INVITER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SendbirdBasicUserInfo getInviter() {
    return inviter;
  }


  @JsonProperty(JSON_PROPERTY_INVITER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInviter(SendbirdBasicUserInfo inviter) {
    this.inviter = inviter;
  }


  public GetAGroupChannelResponse isAccessCodeRequired(Boolean isAccessCodeRequired) {
    this.isAccessCodeRequired = isAccessCodeRequired;
    return this;
  }

   /**
   * Get isAccessCodeRequired
   * @return isAccessCodeRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_ACCESS_CODE_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsAccessCodeRequired() {
    return isAccessCodeRequired;
  }


  @JsonProperty(JSON_PROPERTY_IS_ACCESS_CODE_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAccessCodeRequired(Boolean isAccessCodeRequired) {
    this.isAccessCodeRequired = isAccessCodeRequired;
  }


  public GetAGroupChannelResponse isBroadcast(Boolean isBroadcast) {
    this.isBroadcast = isBroadcast;
    return this;
  }

   /**
   * Get isBroadcast
   * @return isBroadcast
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_BROADCAST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsBroadcast() {
    return isBroadcast;
  }


  @JsonProperty(JSON_PROPERTY_IS_BROADCAST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsBroadcast(Boolean isBroadcast) {
    this.isBroadcast = isBroadcast;
  }


  public GetAGroupChannelResponse isDiscoverable(Boolean isDiscoverable) {
    this.isDiscoverable = isDiscoverable;
    return this;
  }

   /**
   * Get isDiscoverable
   * @return isDiscoverable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_DISCOVERABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDiscoverable() {
    return isDiscoverable;
  }


  @JsonProperty(JSON_PROPERTY_IS_DISCOVERABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDiscoverable(Boolean isDiscoverable) {
    this.isDiscoverable = isDiscoverable;
  }


  public GetAGroupChannelResponse isDistinct(Boolean isDistinct) {
    this.isDistinct = isDistinct;
    return this;
  }

   /**
   * Get isDistinct
   * @return isDistinct
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_DISTINCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDistinct() {
    return isDistinct;
  }


  @JsonProperty(JSON_PROPERTY_IS_DISTINCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDistinct(Boolean isDistinct) {
    this.isDistinct = isDistinct;
  }


  public GetAGroupChannelResponse isEphemeral(Boolean isEphemeral) {
    this.isEphemeral = isEphemeral;
    return this;
  }

   /**
   * Get isEphemeral
   * @return isEphemeral
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_EPHEMERAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsEphemeral() {
    return isEphemeral;
  }


  @JsonProperty(JSON_PROPERTY_IS_EPHEMERAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEphemeral(Boolean isEphemeral) {
    this.isEphemeral = isEphemeral;
  }


  public GetAGroupChannelResponse isExclusive(Boolean isExclusive) {
    this.isExclusive = isExclusive;
    return this;
  }

   /**
   * Get isExclusive
   * @return isExclusive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_EXCLUSIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsExclusive() {
    return isExclusive;
  }


  @JsonProperty(JSON_PROPERTY_IS_EXCLUSIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsExclusive(Boolean isExclusive) {
    this.isExclusive = isExclusive;
  }


  public GetAGroupChannelResponse isHidden(Boolean isHidden) {
    this.isHidden = isHidden;
    return this;
  }

   /**
   * Get isHidden
   * @return isHidden
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsHidden() {
    return isHidden;
  }


  @JsonProperty(JSON_PROPERTY_IS_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsHidden(Boolean isHidden) {
    this.isHidden = isHidden;
  }


  public GetAGroupChannelResponse isMuted(Boolean isMuted) {
    this.isMuted = isMuted;
    return this;
  }

   /**
   * Get isMuted
   * @return isMuted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_MUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsMuted() {
    return isMuted;
  }


  @JsonProperty(JSON_PROPERTY_IS_MUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsMuted(Boolean isMuted) {
    this.isMuted = isMuted;
  }


  public GetAGroupChannelResponse isPublic(Boolean isPublic) {
    this.isPublic = isPublic;
    return this;
  }

   /**
   * Get isPublic
   * @return isPublic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPublic() {
    return isPublic;
  }


  @JsonProperty(JSON_PROPERTY_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPublic(Boolean isPublic) {
    this.isPublic = isPublic;
  }


  public GetAGroupChannelResponse isPushEnabled(Boolean isPushEnabled) {
    this.isPushEnabled = isPushEnabled;
    return this;
  }

   /**
   * Get isPushEnabled
   * @return isPushEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_PUSH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPushEnabled() {
    return isPushEnabled;
  }


  @JsonProperty(JSON_PROPERTY_IS_PUSH_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPushEnabled(Boolean isPushEnabled) {
    this.isPushEnabled = isPushEnabled;
  }


  public GetAGroupChannelResponse isSuper(Boolean isSuper) {
    this.isSuper = isSuper;
    return this;
  }

   /**
   * Get isSuper
   * @return isSuper
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_SUPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSuper() {
    return isSuper;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSuper(Boolean isSuper) {
    this.isSuper = isSuper;
  }


  public GetAGroupChannelResponse joinedMemberCount(Integer joinedMemberCount) {
    this.joinedMemberCount = joinedMemberCount;
    return this;
  }

   /**
   * Get joinedMemberCount
   * @return joinedMemberCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JOINED_MEMBER_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getJoinedMemberCount() {
    return joinedMemberCount;
  }


  @JsonProperty(JSON_PROPERTY_JOINED_MEMBER_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJoinedMemberCount(Integer joinedMemberCount) {
    this.joinedMemberCount = joinedMemberCount;
  }


  public GetAGroupChannelResponse joinedTs(Long joinedTs) {
    this.joinedTs = joinedTs;
    return this;
  }

   /**
   * Get joinedTs
   * @return joinedTs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JOINED_TS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJoinedTs() {
    return joinedTs;
  }


  @JsonProperty(JSON_PROPERTY_JOINED_TS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJoinedTs(Long joinedTs) {
    this.joinedTs = joinedTs;
  }


  public GetAGroupChannelResponse lastMessage(SendbirdMessageResponse lastMessage) {
    this.lastMessage = JsonNullable.<SendbirdMessageResponse>of(lastMessage);
    return this;
  }

   /**
   * Get lastMessage
   * @return lastMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public SendbirdMessageResponse getLastMessage() {
        return lastMessage.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<SendbirdMessageResponse> getLastMessage_JsonNullable() {
    return lastMessage;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_MESSAGE)
  public void setLastMessage_JsonNullable(JsonNullable<SendbirdMessageResponse> lastMessage) {
    this.lastMessage = lastMessage;
  }

  public void setLastMessage(SendbirdMessageResponse lastMessage) {
    this.lastMessage = JsonNullable.<SendbirdMessageResponse>of(lastMessage);
  }


  public GetAGroupChannelResponse maxLengthMessage(Integer maxLengthMessage) {
    this.maxLengthMessage = maxLengthMessage;
    return this;
  }

   /**
   * Get maxLengthMessage
   * @return maxLengthMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAX_LENGTH_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxLengthMessage() {
    return maxLengthMessage;
  }


  @JsonProperty(JSON_PROPERTY_MAX_LENGTH_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxLengthMessage(Integer maxLengthMessage) {
    this.maxLengthMessage = maxLengthMessage;
  }


  public GetAGroupChannelResponse memberCount(Integer memberCount) {
    this.memberCount = memberCount;
    return this;
  }

   /**
   * Get memberCount
   * @return memberCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MEMBER_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMemberCount() {
    return memberCount;
  }


  @JsonProperty(JSON_PROPERTY_MEMBER_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberCount(Integer memberCount) {
    this.memberCount = memberCount;
  }


  public GetAGroupChannelResponse memberState(MemberStateEnum memberState) {
    this.memberState = memberState;
    return this;
  }

   /**
   * Get memberState
   * @return memberState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MEMBER_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MemberStateEnum getMemberState() {
    return memberState;
  }


  @JsonProperty(JSON_PROPERTY_MEMBER_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberState(MemberStateEnum memberState) {
    this.memberState = memberState;
  }


  public GetAGroupChannelResponse members(List<SendbirdMember> members) {
    this.members = members;
    return this;
  }

  public GetAGroupChannelResponse addMembersItem(SendbirdMember membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * Get members
   * @return members
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SendbirdMember> getMembers() {
    return members;
  }


  @JsonProperty(JSON_PROPERTY_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMembers(List<SendbirdMember> members) {
    this.members = members;
  }


  public GetAGroupChannelResponse messageSurvivalSeconds(Integer messageSurvivalSeconds) {
    this.messageSurvivalSeconds = messageSurvivalSeconds;
    return this;
  }

   /**
   * Get messageSurvivalSeconds
   * @return messageSurvivalSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MESSAGE_SURVIVAL_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMessageSurvivalSeconds() {
    return messageSurvivalSeconds;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_SURVIVAL_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageSurvivalSeconds(Integer messageSurvivalSeconds) {
    this.messageSurvivalSeconds = messageSurvivalSeconds;
  }


  public GetAGroupChannelResponse metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  public GetAGroupChannelResponse myRole(MyRoleEnum myRole) {
    this.myRole = myRole;
    return this;
  }

   /**
   * Get myRole
   * @return myRole
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MyRoleEnum getMyRole() {
    return myRole;
  }


  @JsonProperty(JSON_PROPERTY_MY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMyRole(MyRoleEnum myRole) {
    this.myRole = myRole;
  }


  public GetAGroupChannelResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public GetAGroupChannelResponse pushTriggerOption(SendbirdPushTriggerOption pushTriggerOption) {
    this.pushTriggerOption = pushTriggerOption;
    return this;
  }

   /**
   * Get pushTriggerOption
   * @return pushTriggerOption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PUSH_TRIGGER_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SendbirdPushTriggerOption getPushTriggerOption() {
    return pushTriggerOption;
  }


  @JsonProperty(JSON_PROPERTY_PUSH_TRIGGER_OPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPushTriggerOption(SendbirdPushTriggerOption pushTriggerOption) {
    this.pushTriggerOption = pushTriggerOption;
  }


  public GetAGroupChannelResponse readReceipt(Map<String, Long> readReceipt) {
    this.readReceipt = readReceipt;
    return this;
  }

  public GetAGroupChannelResponse putReadReceiptItem(String key, Long readReceiptItem) {
    if (this.readReceipt == null) {
      this.readReceipt = new HashMap<>();
    }
    this.readReceipt.put(key, readReceiptItem);
    return this;
  }

   /**
   * Get readReceipt
   * @return readReceipt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_READ_RECEIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Long> getReadReceipt() {
    return readReceipt;
  }


  @JsonProperty(JSON_PROPERTY_READ_RECEIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReadReceipt(Map<String, Long> readReceipt) {
    this.readReceipt = readReceipt;
  }


  public GetAGroupChannelResponse smsFallback(SendbirdSmsFallback smsFallback) {
    this.smsFallback = smsFallback;
    return this;
  }

   /**
   * Get smsFallback
   * @return smsFallback
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SMS_FALLBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SendbirdSmsFallback getSmsFallback() {
    return smsFallback;
  }


  @JsonProperty(JSON_PROPERTY_SMS_FALLBACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmsFallback(SendbirdSmsFallback smsFallback) {
    this.smsFallback = smsFallback;
  }


  public GetAGroupChannelResponse tsMessageOffset(Long tsMessageOffset) {
    this.tsMessageOffset = tsMessageOffset;
    return this;
  }

   /**
   * Get tsMessageOffset
   * @return tsMessageOffset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TS_MESSAGE_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTsMessageOffset() {
    return tsMessageOffset;
  }


  @JsonProperty(JSON_PROPERTY_TS_MESSAGE_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsMessageOffset(Long tsMessageOffset) {
    this.tsMessageOffset = tsMessageOffset;
  }


  public GetAGroupChannelResponse unreadMentionCount(Integer unreadMentionCount) {
    this.unreadMentionCount = unreadMentionCount;
    return this;
  }

   /**
   * Get unreadMentionCount
   * @return unreadMentionCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNREAD_MENTION_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUnreadMentionCount() {
    return unreadMentionCount;
  }


  @JsonProperty(JSON_PROPERTY_UNREAD_MENTION_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnreadMentionCount(Integer unreadMentionCount) {
    this.unreadMentionCount = unreadMentionCount;
  }


  public GetAGroupChannelResponse unreadMessageCount(Integer unreadMessageCount) {
    this.unreadMessageCount = unreadMessageCount;
    return this;
  }

   /**
   * Get unreadMessageCount
   * @return unreadMessageCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNREAD_MESSAGE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUnreadMessageCount() {
    return unreadMessageCount;
  }


  @JsonProperty(JSON_PROPERTY_UNREAD_MESSAGE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnreadMessageCount(Integer unreadMessageCount) {
    this.unreadMessageCount = unreadMessageCount;
  }


  public GetAGroupChannelResponse userLastRead(Long userLastRead) {
    this.userLastRead = userLastRead;
    return this;
  }

   /**
   * Get userLastRead
   * @return userLastRead
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_LAST_READ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUserLastRead() {
    return userLastRead;
  }


  @JsonProperty(JSON_PROPERTY_USER_LAST_READ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserLastRead(Long userLastRead) {
    this.userLastRead = userLastRead;
  }


  /**
   * Return true if this getAGroupChannelResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAGroupChannelResponse getAGroupChannelResponse = (GetAGroupChannelResponse) o;
    return Objects.equals(this.channel, getAGroupChannelResponse.channel) &&
        Objects.equals(this.channelUrl, getAGroupChannelResponse.channelUrl) &&
        Objects.equals(this.countPreference, getAGroupChannelResponse.countPreference) &&
        Objects.equals(this.coverUrl, getAGroupChannelResponse.coverUrl) &&
        Objects.equals(this.createdAt, getAGroupChannelResponse.createdAt) &&
        Objects.equals(this.createdBy, getAGroupChannelResponse.createdBy) &&
        Objects.equals(this.customType, getAGroupChannelResponse.customType) &&
        Objects.equals(this.data, getAGroupChannelResponse.data) &&
        Objects.equals(this.deliveryReceipt, getAGroupChannelResponse.deliveryReceipt) &&
        Objects.equals(this.disappearingMessage, getAGroupChannelResponse.disappearingMessage) &&
        Objects.equals(this.freeze, getAGroupChannelResponse.freeze) &&
        Objects.equals(this.hasAiBot, getAGroupChannelResponse.hasAiBot) &&
        Objects.equals(this.hasBot, getAGroupChannelResponse.hasBot) &&
        Objects.equals(this.hiddenState, getAGroupChannelResponse.hiddenState) &&
        Objects.equals(this.ignoreProfanityFilter, getAGroupChannelResponse.ignoreProfanityFilter) &&
        Objects.equals(this.invitedAt, getAGroupChannelResponse.invitedAt) &&
        Objects.equals(this.inviter, getAGroupChannelResponse.inviter) &&
        Objects.equals(this.isAccessCodeRequired, getAGroupChannelResponse.isAccessCodeRequired) &&
        Objects.equals(this.isBroadcast, getAGroupChannelResponse.isBroadcast) &&
        Objects.equals(this.isDiscoverable, getAGroupChannelResponse.isDiscoverable) &&
        Objects.equals(this.isDistinct, getAGroupChannelResponse.isDistinct) &&
        Objects.equals(this.isEphemeral, getAGroupChannelResponse.isEphemeral) &&
        Objects.equals(this.isExclusive, getAGroupChannelResponse.isExclusive) &&
        Objects.equals(this.isHidden, getAGroupChannelResponse.isHidden) &&
        Objects.equals(this.isMuted, getAGroupChannelResponse.isMuted) &&
        Objects.equals(this.isPublic, getAGroupChannelResponse.isPublic) &&
        Objects.equals(this.isPushEnabled, getAGroupChannelResponse.isPushEnabled) &&
        Objects.equals(this.isSuper, getAGroupChannelResponse.isSuper) &&
        Objects.equals(this.joinedMemberCount, getAGroupChannelResponse.joinedMemberCount) &&
        Objects.equals(this.joinedTs, getAGroupChannelResponse.joinedTs) &&
        equalsNullable(this.lastMessage, getAGroupChannelResponse.lastMessage) &&
        Objects.equals(this.maxLengthMessage, getAGroupChannelResponse.maxLengthMessage) &&
        Objects.equals(this.memberCount, getAGroupChannelResponse.memberCount) &&
        Objects.equals(this.memberState, getAGroupChannelResponse.memberState) &&
        Objects.equals(this.members, getAGroupChannelResponse.members) &&
        Objects.equals(this.messageSurvivalSeconds, getAGroupChannelResponse.messageSurvivalSeconds) &&
        Objects.equals(this.metadata, getAGroupChannelResponse.metadata) &&
        Objects.equals(this.myRole, getAGroupChannelResponse.myRole) &&
        Objects.equals(this.name, getAGroupChannelResponse.name) &&
        Objects.equals(this.pushTriggerOption, getAGroupChannelResponse.pushTriggerOption) &&
        Objects.equals(this.readReceipt, getAGroupChannelResponse.readReceipt) &&
        Objects.equals(this.smsFallback, getAGroupChannelResponse.smsFallback) &&
        Objects.equals(this.tsMessageOffset, getAGroupChannelResponse.tsMessageOffset) &&
        Objects.equals(this.unreadMentionCount, getAGroupChannelResponse.unreadMentionCount) &&
        Objects.equals(this.unreadMessageCount, getAGroupChannelResponse.unreadMessageCount) &&
        Objects.equals(this.userLastRead, getAGroupChannelResponse.userLastRead);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, channelUrl, countPreference, coverUrl, createdAt, createdBy, customType, data, deliveryReceipt, disappearingMessage, freeze, hasAiBot, hasBot, hiddenState, ignoreProfanityFilter, invitedAt, inviter, isAccessCodeRequired, isBroadcast, isDiscoverable, isDistinct, isEphemeral, isExclusive, isHidden, isMuted, isPublic, isPushEnabled, isSuper, joinedMemberCount, joinedTs, hashCodeNullable(lastMessage), maxLengthMessage, memberCount, memberState, members, messageSurvivalSeconds, metadata, myRole, name, pushTriggerOption, readReceipt, smsFallback, tsMessageOffset, unreadMentionCount, unreadMessageCount, userLastRead);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAGroupChannelResponse {\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    channelUrl: ").append(toIndentedString(channelUrl)).append("\n");
    sb.append("    countPreference: ").append(toIndentedString(countPreference)).append("\n");
    sb.append("    coverUrl: ").append(toIndentedString(coverUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    customType: ").append(toIndentedString(customType)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    deliveryReceipt: ").append(toIndentedString(deliveryReceipt)).append("\n");
    sb.append("    disappearingMessage: ").append(toIndentedString(disappearingMessage)).append("\n");
    sb.append("    freeze: ").append(toIndentedString(freeze)).append("\n");
    sb.append("    hasAiBot: ").append(toIndentedString(hasAiBot)).append("\n");
    sb.append("    hasBot: ").append(toIndentedString(hasBot)).append("\n");
    sb.append("    hiddenState: ").append(toIndentedString(hiddenState)).append("\n");
    sb.append("    ignoreProfanityFilter: ").append(toIndentedString(ignoreProfanityFilter)).append("\n");
    sb.append("    invitedAt: ").append(toIndentedString(invitedAt)).append("\n");
    sb.append("    inviter: ").append(toIndentedString(inviter)).append("\n");
    sb.append("    isAccessCodeRequired: ").append(toIndentedString(isAccessCodeRequired)).append("\n");
    sb.append("    isBroadcast: ").append(toIndentedString(isBroadcast)).append("\n");
    sb.append("    isDiscoverable: ").append(toIndentedString(isDiscoverable)).append("\n");
    sb.append("    isDistinct: ").append(toIndentedString(isDistinct)).append("\n");
    sb.append("    isEphemeral: ").append(toIndentedString(isEphemeral)).append("\n");
    sb.append("    isExclusive: ").append(toIndentedString(isExclusive)).append("\n");
    sb.append("    isHidden: ").append(toIndentedString(isHidden)).append("\n");
    sb.append("    isMuted: ").append(toIndentedString(isMuted)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    isPushEnabled: ").append(toIndentedString(isPushEnabled)).append("\n");
    sb.append("    isSuper: ").append(toIndentedString(isSuper)).append("\n");
    sb.append("    joinedMemberCount: ").append(toIndentedString(joinedMemberCount)).append("\n");
    sb.append("    joinedTs: ").append(toIndentedString(joinedTs)).append("\n");
    sb.append("    lastMessage: ").append(toIndentedString(lastMessage)).append("\n");
    sb.append("    maxLengthMessage: ").append(toIndentedString(maxLengthMessage)).append("\n");
    sb.append("    memberCount: ").append(toIndentedString(memberCount)).append("\n");
    sb.append("    memberState: ").append(toIndentedString(memberState)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    messageSurvivalSeconds: ").append(toIndentedString(messageSurvivalSeconds)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    myRole: ").append(toIndentedString(myRole)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pushTriggerOption: ").append(toIndentedString(pushTriggerOption)).append("\n");
    sb.append("    readReceipt: ").append(toIndentedString(readReceipt)).append("\n");
    sb.append("    smsFallback: ").append(toIndentedString(smsFallback)).append("\n");
    sb.append("    tsMessageOffset: ").append(toIndentedString(tsMessageOffset)).append("\n");
    sb.append("    unreadMentionCount: ").append(toIndentedString(unreadMentionCount)).append("\n");
    sb.append("    unreadMessageCount: ").append(toIndentedString(unreadMessageCount)).append("\n");
    sb.append("    userLastRead: ").append(toIndentedString(userLastRead)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

