/*
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.sendbird.client.JSON;

/**
 * GetStatisticsDailyResponseStatisticsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-27T16:53:12.807119+01:00[Europe/London]")
public class GetStatisticsDailyResponseStatisticsInner {
  public static final String SERIALIZED_NAME_DATE_RANGE = "date_range";
  @SerializedName(SERIALIZED_NAME_DATE_RANGE)
  private String dateRange;

  public static final String SERIALIZED_NAME_CANCELED_ANNOUNCEMENT_COUNT = "canceled_announcement_count";
  @SerializedName(SERIALIZED_NAME_CANCELED_ANNOUNCEMENT_COUNT)
  private BigDecimal canceledAnnouncementCount;

  public static final String SERIALIZED_NAME_STOPPED_ANNOUNCEMENT_COUNT = "stopped_announcement_count";
  @SerializedName(SERIALIZED_NAME_STOPPED_ANNOUNCEMENT_COUNT)
  private BigDecimal stoppedAnnouncementCount;

  public static final String SERIALIZED_NAME_COMPLETED_ANNOUNCEMENT_COUNT = "completed_announcement_count";
  @SerializedName(SERIALIZED_NAME_COMPLETED_ANNOUNCEMENT_COUNT)
  private BigDecimal completedAnnouncementCount;

  public static final String SERIALIZED_NAME_TOTAL_ANNOUNCEMENT_COUNT = "total_announcement_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_ANNOUNCEMENT_COUNT)
  private BigDecimal totalAnnouncementCount;

  public static final String SERIALIZED_NAME_TARGET_CHANNEL_COUNT = "target_channel_count";
  @SerializedName(SERIALIZED_NAME_TARGET_CHANNEL_COUNT)
  private BigDecimal targetChannelCount;

  public static final String SERIALIZED_NAME_TARGET_USER_COUNT = "target_user_count";
  @SerializedName(SERIALIZED_NAME_TARGET_USER_COUNT)
  private BigDecimal targetUserCount;

  public static final String SERIALIZED_NAME_SENT_CHANNEL_COUNT = "sent_channel_count";
  @SerializedName(SERIALIZED_NAME_SENT_CHANNEL_COUNT)
  private BigDecimal sentChannelCount;

  public static final String SERIALIZED_NAME_SENT_USER_COUNT = "sent_user_count";
  @SerializedName(SERIALIZED_NAME_SENT_USER_COUNT)
  private BigDecimal sentUserCount;

  public static final String SERIALIZED_NAME_OPEN_RATE = "open_rate";
  @SerializedName(SERIALIZED_NAME_OPEN_RATE)
  private BigDecimal openRate;

  public static final String SERIALIZED_NAME_OPEN_COUNT = "open_count";
  @SerializedName(SERIALIZED_NAME_OPEN_COUNT)
  private BigDecimal openCount;

  public GetStatisticsDailyResponseStatisticsInner() { 
  }

  public GetStatisticsDailyResponseStatisticsInner dateRange(String dateRange) {
    
    this.dateRange = dateRange;
    return this;
  }

   /**
   * Get dateRange
   * @return dateRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDateRange() {
    return dateRange;
  }


  public void setDateRange(String dateRange) {
    this.dateRange = dateRange;
  }


  public GetStatisticsDailyResponseStatisticsInner canceledAnnouncementCount(BigDecimal canceledAnnouncementCount) {
    
    this.canceledAnnouncementCount = canceledAnnouncementCount;
    return this;
  }

   /**
   * Get canceledAnnouncementCount
   * @return canceledAnnouncementCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getCanceledAnnouncementCount() {
    return canceledAnnouncementCount;
  }


  public void setCanceledAnnouncementCount(BigDecimal canceledAnnouncementCount) {
    this.canceledAnnouncementCount = canceledAnnouncementCount;
  }


  public GetStatisticsDailyResponseStatisticsInner stoppedAnnouncementCount(BigDecimal stoppedAnnouncementCount) {
    
    this.stoppedAnnouncementCount = stoppedAnnouncementCount;
    return this;
  }

   /**
   * Get stoppedAnnouncementCount
   * @return stoppedAnnouncementCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getStoppedAnnouncementCount() {
    return stoppedAnnouncementCount;
  }


  public void setStoppedAnnouncementCount(BigDecimal stoppedAnnouncementCount) {
    this.stoppedAnnouncementCount = stoppedAnnouncementCount;
  }


  public GetStatisticsDailyResponseStatisticsInner completedAnnouncementCount(BigDecimal completedAnnouncementCount) {
    
    this.completedAnnouncementCount = completedAnnouncementCount;
    return this;
  }

   /**
   * Get completedAnnouncementCount
   * @return completedAnnouncementCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getCompletedAnnouncementCount() {
    return completedAnnouncementCount;
  }


  public void setCompletedAnnouncementCount(BigDecimal completedAnnouncementCount) {
    this.completedAnnouncementCount = completedAnnouncementCount;
  }


  public GetStatisticsDailyResponseStatisticsInner totalAnnouncementCount(BigDecimal totalAnnouncementCount) {
    
    this.totalAnnouncementCount = totalAnnouncementCount;
    return this;
  }

   /**
   * Get totalAnnouncementCount
   * @return totalAnnouncementCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTotalAnnouncementCount() {
    return totalAnnouncementCount;
  }


  public void setTotalAnnouncementCount(BigDecimal totalAnnouncementCount) {
    this.totalAnnouncementCount = totalAnnouncementCount;
  }


  public GetStatisticsDailyResponseStatisticsInner targetChannelCount(BigDecimal targetChannelCount) {
    
    this.targetChannelCount = targetChannelCount;
    return this;
  }

   /**
   * Get targetChannelCount
   * @return targetChannelCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTargetChannelCount() {
    return targetChannelCount;
  }


  public void setTargetChannelCount(BigDecimal targetChannelCount) {
    this.targetChannelCount = targetChannelCount;
  }


  public GetStatisticsDailyResponseStatisticsInner targetUserCount(BigDecimal targetUserCount) {
    
    this.targetUserCount = targetUserCount;
    return this;
  }

   /**
   * Get targetUserCount
   * @return targetUserCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getTargetUserCount() {
    return targetUserCount;
  }


  public void setTargetUserCount(BigDecimal targetUserCount) {
    this.targetUserCount = targetUserCount;
  }


  public GetStatisticsDailyResponseStatisticsInner sentChannelCount(BigDecimal sentChannelCount) {
    
    this.sentChannelCount = sentChannelCount;
    return this;
  }

   /**
   * Get sentChannelCount
   * @return sentChannelCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getSentChannelCount() {
    return sentChannelCount;
  }


  public void setSentChannelCount(BigDecimal sentChannelCount) {
    this.sentChannelCount = sentChannelCount;
  }


  public GetStatisticsDailyResponseStatisticsInner sentUserCount(BigDecimal sentUserCount) {
    
    this.sentUserCount = sentUserCount;
    return this;
  }

   /**
   * Get sentUserCount
   * @return sentUserCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getSentUserCount() {
    return sentUserCount;
  }


  public void setSentUserCount(BigDecimal sentUserCount) {
    this.sentUserCount = sentUserCount;
  }


  public GetStatisticsDailyResponseStatisticsInner openRate(BigDecimal openRate) {
    
    this.openRate = openRate;
    return this;
  }

   /**
   * Get openRate
   * @return openRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getOpenRate() {
    return openRate;
  }


  public void setOpenRate(BigDecimal openRate) {
    this.openRate = openRate;
  }


  public GetStatisticsDailyResponseStatisticsInner openCount(BigDecimal openCount) {
    
    this.openCount = openCount;
    return this;
  }

   /**
   * Get openCount
   * @return openCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getOpenCount() {
    return openCount;
  }


  public void setOpenCount(BigDecimal openCount) {
    this.openCount = openCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetStatisticsDailyResponseStatisticsInner getStatisticsDailyResponseStatisticsInner = (GetStatisticsDailyResponseStatisticsInner) o;
    return Objects.equals(this.dateRange, getStatisticsDailyResponseStatisticsInner.dateRange) &&
        Objects.equals(this.canceledAnnouncementCount, getStatisticsDailyResponseStatisticsInner.canceledAnnouncementCount) &&
        Objects.equals(this.stoppedAnnouncementCount, getStatisticsDailyResponseStatisticsInner.stoppedAnnouncementCount) &&
        Objects.equals(this.completedAnnouncementCount, getStatisticsDailyResponseStatisticsInner.completedAnnouncementCount) &&
        Objects.equals(this.totalAnnouncementCount, getStatisticsDailyResponseStatisticsInner.totalAnnouncementCount) &&
        Objects.equals(this.targetChannelCount, getStatisticsDailyResponseStatisticsInner.targetChannelCount) &&
        Objects.equals(this.targetUserCount, getStatisticsDailyResponseStatisticsInner.targetUserCount) &&
        Objects.equals(this.sentChannelCount, getStatisticsDailyResponseStatisticsInner.sentChannelCount) &&
        Objects.equals(this.sentUserCount, getStatisticsDailyResponseStatisticsInner.sentUserCount) &&
        Objects.equals(this.openRate, getStatisticsDailyResponseStatisticsInner.openRate) &&
        Objects.equals(this.openCount, getStatisticsDailyResponseStatisticsInner.openCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateRange, canceledAnnouncementCount, stoppedAnnouncementCount, completedAnnouncementCount, totalAnnouncementCount, targetChannelCount, targetUserCount, sentChannelCount, sentUserCount, openRate, openCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStatisticsDailyResponseStatisticsInner {\n");
    sb.append("    dateRange: ").append(toIndentedString(dateRange)).append("\n");
    sb.append("    canceledAnnouncementCount: ").append(toIndentedString(canceledAnnouncementCount)).append("\n");
    sb.append("    stoppedAnnouncementCount: ").append(toIndentedString(stoppedAnnouncementCount)).append("\n");
    sb.append("    completedAnnouncementCount: ").append(toIndentedString(completedAnnouncementCount)).append("\n");
    sb.append("    totalAnnouncementCount: ").append(toIndentedString(totalAnnouncementCount)).append("\n");
    sb.append("    targetChannelCount: ").append(toIndentedString(targetChannelCount)).append("\n");
    sb.append("    targetUserCount: ").append(toIndentedString(targetUserCount)).append("\n");
    sb.append("    sentChannelCount: ").append(toIndentedString(sentChannelCount)).append("\n");
    sb.append("    sentUserCount: ").append(toIndentedString(sentUserCount)).append("\n");
    sb.append("    openRate: ").append(toIndentedString(openRate)).append("\n");
    sb.append("    openCount: ").append(toIndentedString(openCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date_range");
    openapiFields.add("canceled_announcement_count");
    openapiFields.add("stopped_announcement_count");
    openapiFields.add("completed_announcement_count");
    openapiFields.add("total_announcement_count");
    openapiFields.add("target_channel_count");
    openapiFields.add("target_user_count");
    openapiFields.add("sent_channel_count");
    openapiFields.add("sent_user_count");
    openapiFields.add("open_rate");
    openapiFields.add("open_count");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetStatisticsDailyResponseStatisticsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (GetStatisticsDailyResponseStatisticsInner.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetStatisticsDailyResponseStatisticsInner is not found in the empty JSON string", GetStatisticsDailyResponseStatisticsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetStatisticsDailyResponseStatisticsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetStatisticsDailyResponseStatisticsInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("date_range") != null && !jsonObj.get("date_range").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date_range` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_range").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetStatisticsDailyResponseStatisticsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetStatisticsDailyResponseStatisticsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetStatisticsDailyResponseStatisticsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetStatisticsDailyResponseStatisticsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetStatisticsDailyResponseStatisticsInner>() {
           @Override
           public void write(JsonWriter out, GetStatisticsDailyResponseStatisticsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetStatisticsDailyResponseStatisticsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetStatisticsDailyResponseStatisticsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetStatisticsDailyResponseStatisticsInner
  * @throws IOException if the JSON string is invalid with respect to GetStatisticsDailyResponseStatisticsInner
  */
  public static GetStatisticsDailyResponseStatisticsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetStatisticsDailyResponseStatisticsInner.class);
  }

 /**
  * Convert an instance of GetStatisticsDailyResponseStatisticsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

