/*
 * Sendbird Platform SDK
 * Sendbird Platform API SDK  [https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api](https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api)  Contact Support:   Name: Sendbird   Email: [support@sendbird.com](https://mailto:support@sendbird.com)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@sendbird.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.sendbird.client.JSON;


/**
 * UpdateCountPreferenceOfAChannelRequest
 */
@JsonPropertyOrder({
  UpdateCountPreferenceOfAChannelRequest.JSON_PROPERTY_COUNT_PREFERENCE
})
@JsonTypeName("updateCountPreferenceOfAChannel_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T07:36:12.748535+07:00[Asia/Jakarta]")
public class UpdateCountPreferenceOfAChannelRequest {
  /**
   * Gets or Sets countPreference
   */
  public enum CountPreferenceEnum {
    FALSE("false"),
    
    ALL("all"),
    
    UNREAD_MESSAGE_COUNT_ONLY("unread_message_count_only"),
    
    UNREAD_MENTIONED_COUNT_ONLY("unread_mentioned_count_only");

    private String value;

    CountPreferenceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CountPreferenceEnum fromValue(String value) {
      for (CountPreferenceEnum b : CountPreferenceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COUNT_PREFERENCE = "count_preference";
  private CountPreferenceEnum countPreference;

  public UpdateCountPreferenceOfAChannelRequest() { 
  }

  public UpdateCountPreferenceOfAChannelRequest countPreference(CountPreferenceEnum countPreference) {
    this.countPreference = countPreference;
    return this;
  }

   /**
   * Get countPreference
   * @return countPreference
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COUNT_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CountPreferenceEnum getCountPreference() {
    return countPreference;
  }


  @JsonProperty(JSON_PROPERTY_COUNT_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountPreference(CountPreferenceEnum countPreference) {
    this.countPreference = countPreference;
  }


  /**
   * Return true if this updateCountPreferenceOfAChannel_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCountPreferenceOfAChannelRequest updateCountPreferenceOfAChannelRequest = (UpdateCountPreferenceOfAChannelRequest) o;
    return Objects.equals(this.countPreference, updateCountPreferenceOfAChannelRequest.countPreference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countPreference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCountPreferenceOfAChannelRequest {\n");
    sb.append("    countPreference: ").append(toIndentedString(countPreference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

