/*
 * Sendbird Platform SDK
 * Sendbird Platform API Javascript SDK  https://sendbird.com/docs/chat/v3/platform-api/getting-started/prepare-to-use-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ViewNumberOfPeakConnectionsResponsePeakConnections;

/**
 * ViewNumberOfPeakConnectionsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-29T11:00:21.022543+01:00[Europe/London]")
public class ViewNumberOfPeakConnectionsResponse {
  public static final String SERIALIZED_NAME_PEAK_CONNECTIONS = "peak_connections";
  @SerializedName(SERIALIZED_NAME_PEAK_CONNECTIONS)
  private List<ViewNumberOfPeakConnectionsResponsePeakConnections> peakConnections = null;

  public ViewNumberOfPeakConnectionsResponse() { 
  }

  public ViewNumberOfPeakConnectionsResponse peakConnections(List<ViewNumberOfPeakConnectionsResponsePeakConnections> peakConnections) {
    
    this.peakConnections = peakConnections;
    return this;
  }

  public ViewNumberOfPeakConnectionsResponse addPeakConnectionsItem(ViewNumberOfPeakConnectionsResponsePeakConnections peakConnectionsItem) {
    if (this.peakConnections == null) {
      this.peakConnections = new ArrayList<ViewNumberOfPeakConnectionsResponsePeakConnections>();
    }
    this.peakConnections.add(peakConnectionsItem);
    return this;
  }

   /**
   * Get peakConnections
   * @return peakConnections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ViewNumberOfPeakConnectionsResponsePeakConnections> getPeakConnections() {
    return peakConnections;
  }


  public void setPeakConnections(List<ViewNumberOfPeakConnectionsResponsePeakConnections> peakConnections) {
    this.peakConnections = peakConnections;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViewNumberOfPeakConnectionsResponse viewNumberOfPeakConnectionsResponse = (ViewNumberOfPeakConnectionsResponse) o;
    return Objects.equals(this.peakConnections, viewNumberOfPeakConnectionsResponse.peakConnections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(peakConnections);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViewNumberOfPeakConnectionsResponse {\n");
    sb.append("    peakConnections: ").append(toIndentedString(peakConnections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

